const SIGNAL_TYPES = {
  INTRADAY_LONG: "INTRADAY_LONG",
  INTRADAY_SHORT: "INTRADAY_SHORT",
  WAIT_FOR_BREAKOUT: "WAIT_FOR_BREAKOUT",
  WAIT_FOR_PULLBACK: "WAIT_FOR_PULLBACK",
  NO_TRADE: "NO_TRADE",
  AVOID: "AVOID",
};

const TRADE_ACTIONS = {
  BUY: "BUY",
  SELL: "SELL",
  WAIT: "WAIT",
  NONE: "NONE",
  AVOID: "AVOID",
};

const ACTIONABLE_SIGNAL_TYPES = new Set([
  SIGNAL_TYPES.INTRADAY_LONG,
  SIGNAL_TYPES.INTRADAY_SHORT,
]);

module.exports = {
  ACTIONABLE_SIGNAL_TYPES,
  SIGNAL_TYPES,
  TRADE_ACTIONS,
};
